version: "3"
services:
  trovamascherine-db-dev:
    volumes:
      - ./config/db-users-dev.sql:/docker-entrypoint-initdb.d/01-db-users-dev.sql
      - ./config/create-schemas.sql:/docker-entrypoint-initdb.d/02-create-schemas.sql
    image: postgis/postgis:10-3.0-alpine
    ports:
      - 9001:5432
    environment:
      POSTGRES_DB: trovamascherine
      POSTGRES_PASSWORD: trovamascherine
    command: -c 'max_connections=512'
  trovamascherine-db-test:
    volumes:
      - ./config/db-users-dev.sql:/docker-entrypoint-initdb.d/01-db-users-dev.sql
      - ./config/create-schemas.sql:/docker-entrypoint-initdb.d/02-create-schemas.sql
    image: postgis/postgis:10-3.0-alpine
    ports:
      - 9002:5432
    environment:
      POSTGRES_DB: trovamascherine
      POSTGRES_PASSWORD: trovamascherine
    command: -c 'max_connections=512'
